#! /bin/bash

echo -n1 -p " do you want to make(y/n)"
read
if [ $REPLY='y' ]
then
	if (make)
	then 
		echo "make success"
	else
		echo "make failure"
	fi
fi


echo -n1 -p "do you want to insert driver(y/n)"
read
if [ $REPLY='y' ]
then 
	insmod ./modules/blkdd.ko 
	read
	dmesg
	read
	cat /proc/devices
	read 
	cat /proc/modules
fi

echo -n1 -p "do you want to remove driver(y/n)"
read
if [ $REPLY='y' ]
then 
	rmmod blkdd
	read
	dmesg
	read
	cat /proc/devices
	read
	cat /proc/modules
fi

